CREATE TABLE `anamneses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`age` int,
	`height` varchar(10),
	`currentWeight` varchar(10),
	`targetWeight` varchar(10),
	`gender` varchar(20),
	`primaryGoal` text,
	`secondaryGoals` text,
	`trainingExperience` text,
	`currentTrainingFrequency` varchar(50),
	`previousInjuries` text,
	`medicalRestrictions` text,
	`exerciseRestrictions` text,
	`availableDays` text,
	`sessionDuration` varchar(50),
	`occupation` varchar(100),
	`activityLevel` varchar(50),
	`sleepHours` varchar(20),
	`stressLevel` varchar(20),
	`dietType` varchar(50),
	`supplementation` text,
	`chest` varchar(10),
	`waist` varchar(10),
	`hips` varchar(10),
	`thigh` varchar(10),
	`arm` varchar(10),
	`bodyFat` varchar(10),
	`additionalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `anamneses_id` PRIMARY KEY(`id`)
);
