CREATE TABLE `saved_diets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`objective` enum('bulking','cutting','manutencao','recomposicao') NOT NULL,
	`content` text NOT NULL,
	`weight` varchar(10),
	`height` varchar(10),
	`age` int,
	`gender` varchar(20),
	`activityLevel` varchar(50),
	`restrictions` text,
	`preferences` text,
	`targetCalories` int,
	`targetProtein` int,
	`targetCarbs` int,
	`targetFat` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `saved_diets_id` PRIMARY KEY(`id`)
);
